default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: heroku-pg-test
  password: foobar

development:
  <<: *default
  database: heroku-pg-test_development

test:
  <<: *default
  database: heroku-pg-test_test

production:
  <<: *default
  database: heroku-pg-test_production